/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AltaClientePersona.java
 *
 * Created on 07-jul-2009, 18:33:07
 */
package Clientes;

import java.awt.event.KeyEvent;
import java.text.DateFormat;
import java.util.GregorianCalendar;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JRadioButton;
import javax.swing.JTextField;

/**
 *
 * @author Alvaro Gili
 */
public class AltaClientePersona extends javax.swing.JDialog {

    /** Creates new form AltaClientePersona */
    public AltaClientePersona(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        for (int i = 1; i <= 31; i++) {
            jComboBoxDia.addItem(i);
        }
        jComboBoxDia.setSelectedIndex(-1);
        jComboBoxMes.setSelectedIndex(-1);
        provinciaComboBox.setSelectedIndex(-1);

    }

    public void setTitulo(String title) {
        this.setTitle(title);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupdni_cuil = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        direccionClientejTextField = new javax.swing.JTextField();
        dniClientejTextField = new javax.swing.JTextField();
        correoClientejTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        telefonoClientejTextField = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        codPostnClientejTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jRadioButtonDNI = new javax.swing.JRadioButton();
        jRadioButtonCUIL = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        apellidoClientejTextField = new javax.swing.JTextField();
        localidadClientejTextField = new javax.swing.JTextField();
        provinciaComboBox = new javax.swing.JComboBox();
        telefono2ClientejTextField = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        faxClientejTextField = new javax.swing.JTextField();
        primeraParteCuit = new javax.swing.JTextField();
        segundaParteCuit = new javax.swing.JTextField();
        terceraParteCuit = new javax.swing.JTextField();
        nombreClientejTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jComboBoxDia = new javax.swing.JComboBox();
        jComboBoxMes = new javax.swing.JComboBox();
        jLabel15 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Nuevo Cliente");
        setModal(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        dniClientejTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        dniClientejTextField.setToolTipText("");

        correoClientejTextField.setToolTipText("ejemplo: juanperugia@gmail.com");

        jLabel1.setText("*Nombre:");

        jLabel8.setText("Correo:");

        jLabel9.setText("Tel. Principal:");

        jLabel11.setText("Código Postal:");

        jLabel3.setText("Dirección:");

        buttonGroupdni_cuil.add(jRadioButtonDNI);
        jRadioButtonDNI.setSelected(true);
        jRadioButtonDNI.setText("*DNI:");
        jRadioButtonDNI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonDNIActionPerformed(evt);
            }
        });
        jRadioButtonDNI.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jRadioButtonDNIKeyReleased(evt);
            }
        });

        buttonGroupdni_cuil.add(jRadioButtonCUIL);
        jRadioButtonCUIL.setText("*CUIL/CUIT:");
        jRadioButtonCUIL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonCUILActionPerformed(evt);
            }
        });

        jLabel10.setText("Localidad:");

        jLabel6.setText("Provincia:");

        jLabel5.setText("Tel. Alter:");
        jLabel5.setToolTipText("Teléfono Alternativo");

        jLabel4.setText("Fax:");

        provinciaComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Buenos Aires", "Capital Federal", "Catamarca", "Chaco", "Chubut", "Córdoba", "Corrientes", "Entre Ríos", "Formosa", "Jujuy", "La Pampa", "La Rioja", "Mendoza", "Misiones", "Neuquén", "Río Negro", "Salta", "San Juan", "San Luis", "Santa Cruz", "Santa Fé", "Santiago del Estero", "Tierra del Fuego", "Tucumán" }));

        telefono2ClientejTextField.setToolTipText("Teléfono Alternativo");

        jLabel12.setText(" - ");

        jLabel7.setText(" - ");

        primeraParteCuit.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        primeraParteCuit.setEnabled(false);
        primeraParteCuit.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                primeraParteCuitKeyReleased(evt);
            }
        });

        segundaParteCuit.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        segundaParteCuit.setEnabled(false);
        segundaParteCuit.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                segundaParteCuitKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                segundaParteCuitKeyReleased(evt);
            }
        });

        terceraParteCuit.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        terceraParteCuit.setEnabled(false);
        terceraParteCuit.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                terceraParteCuitKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                terceraParteCuitKeyReleased(evt);
            }
        });

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("*Apellido:");

        jLabel14.setText("Cumpleaños:");

        jComboBoxMes.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre" }));
        jComboBoxMes.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxMesItemStateChanged(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Tahoma", 2, 11));
        jLabel15.setText("Los campos marcados con * son obligatorios");

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel11)
                            .add(jLabel3)
                            .add(jLabel9)
                            .add(jLabel8)
                            .add(jRadioButtonDNI)
                            .add(jLabel2))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                                .add(direccionClientejTextField, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                                .add(correoClientejTextField, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                                .add(org.jdesktop.layout.GroupLayout.TRAILING, telefonoClientejTextField, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                                .add(org.jdesktop.layout.GroupLayout.TRAILING, codPostnClientejTextField, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE))
                            .add(dniClientejTextField, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                            .add(apellidoClientejTextField, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jLabel15, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE))
                .add(18, 18, 18)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                        .add(jLabel6)
                        .add(jLabel10, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(jLabel5, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(jLabel4)
                        .add(jLabel14))
                    .add(jRadioButtonCUIL, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 94, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel1))
                .add(24, 24, 24)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(jComboBoxDia, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 57, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(jComboBoxMes, 0, 113, Short.MAX_VALUE))
                    .add(nombreClientejTextField, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, faxClientejTextField, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, telefono2ClientejTextField, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, provinciaComboBox, 0, 180, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1Layout.createSequentialGroup()
                        .add(primeraParteCuit, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jLabel7)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(segundaParteCuit, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 98, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jLabel12)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(terceraParteCuit, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, localidadClientejTextField, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(apellidoClientejTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(nombreClientejTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel1)
                    .add(jLabel2))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jRadioButtonDNI)
                    .add(dniClientejTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(terceraParteCuit, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel12)
                    .add(segundaParteCuit, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel7)
                    .add(primeraParteCuit, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jRadioButtonCUIL))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel3)
                    .add(direccionClientejTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel10)
                    .add(localidadClientejTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(codPostnClientejTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel11)
                    .add(jLabel6)
                    .add(provinciaComboBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(telefonoClientejTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel9)
                    .add(jLabel5)
                    .add(telefono2ClientejTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel8)
                    .add(correoClientejTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel4)
                    .add(faxClientejTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jComboBoxMes, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel15)
                    .add(jLabel14)
                    .add(jComboBoxDia, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/dialog-ok-apply.png"))); // NOI18N
        jButton1.setText("Guardar");

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/application-exit.png"))); // NOI18N
        jButton2.setText("Cancelar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/list-add-user32.png"))); // NOI18N

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(layout.createSequentialGroup()
                        .add(jLabel13)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 347, Short.MAX_VALUE)
                        .add(jButton1)
                        .add(18, 18, 18)
                        .add(jButton2)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jButton2)
                    .add(jButton1)
                    .add(jLabel13))
                .addContainerGap())
        );

        getAccessibleContext().setAccessibleParent(this);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public JTextField getApellidoClientejTextField() {
        return apellidoClientejTextField;
    }

    public JTextField getCodPostnClientejTextField() {
        return codPostnClientejTextField;
    }

    public JTextField getCorreoClientejTextField() {
        return correoClientejTextField;
    }

    public JTextField getDireccionClientejTextField() {
        return direccionClientejTextField;
    }

    public JTextField getDniClientejTextField() {
        return dniClientejTextField;
    }

    public JTextField getFaxClientejTextField() {
        return faxClientejTextField;
    }

    public JButton getjButton1() {
        return jButton1;
    }

    public JButton getjButton2() {
        return jButton2;
    }

    public JRadioButton getjRadioButtonCUIL() {
        return jRadioButtonCUIL;
    }

    public JRadioButton getjRadioButtonDNI() {
        return jRadioButtonDNI;
    }

    public JTextField getLocalidadClientejTextField() {
        return localidadClientejTextField;
    }

    public JTextField getNombreClientejTextField() {
        return nombreClientejTextField;
    }

    public JTextField getPrimeraParteCuit() {
        return primeraParteCuit;
    }

    public JComboBox getProvinciaComboBox() {
        return provinciaComboBox;
    }

    public JTextField getSegundaParteCuit() {
        return segundaParteCuit;
    }

    public JTextField getTelefono2ClientejTextField() {
        return telefono2ClientejTextField;
    }

    public JTextField getTelefonoClientejTextField() {
        return telefonoClientejTextField;
    }

    public JTextField getTerceraParteCuit() {
        return terceraParteCuit;
    }

    public JComboBox getjComboBoxDia() {
        return jComboBoxDia;
    }

    public void setjComboBoxDia(JComboBox jComboBoxDia) {
        this.jComboBoxDia = jComboBoxDia;
    }

    public JComboBox getjComboBoxMes() {
        return jComboBoxMes;
    }

    public void setjComboBoxMes(JComboBox jComboBoxMes) {
        this.jComboBoxMes = jComboBoxMes;
    }

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        if (JOptionPane.showConfirmDialog(this, "El Cliente no se va a guardar, ¿Desea cerrar de todas maneras?",
                "Advertencia", JOptionPane.YES_OPTION, JOptionPane.QUESTION_MESSAGE,
                new ImageIcon(getClass().getResource("/img/important.png"))) == JOptionPane.OK_OPTION) {
            canceled = true;
            this.dispose();
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        if (JOptionPane.showConfirmDialog(this, "El Cliente no se va a guardar, ¿Desea cerrar de todas maneras?",
                "Advertencia", JOptionPane.YES_OPTION, JOptionPane.QUESTION_MESSAGE,
                new ImageIcon(getClass().getResource("/img/important.png"))) == JOptionPane.OK_OPTION) {
            canceled = true;
            this.dispose();
        }
    }//GEN-LAST:event_formWindowClosing

    private void jRadioButtonDNIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonDNIActionPerformed
        if (jRadioButtonDNI.isSelected()) {//deshabilito CUIT
            primeraParteCuit.setEnabled(false);
            segundaParteCuit.setEnabled(false);
            terceraParteCuit.setEnabled(false);
            dniClientejTextField.setEnabled(true);
        }
    }//GEN-LAST:event_jRadioButtonDNIActionPerformed

    private void jRadioButtonCUILActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonCUILActionPerformed
        if (jRadioButtonCUIL.isSelected()) {//deshabilito DNI
            primeraParteCuit.setEnabled(true);
            segundaParteCuit.setEnabled(true);
            terceraParteCuit.setEnabled(true);
            primeraParteCuit.setFocusable(true);
            primeraParteCuit.requestFocusInWindow();
            dniClientejTextField.setEnabled(false);
        }
    }//GEN-LAST:event_jRadioButtonCUILActionPerformed

    private void primeraParteCuitKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_primeraParteCuitKeyReleased
        String texto = primeraParteCuit.getText();
        if (texto.length() == 2 && evt.getKeyCode() != KeyEvent.VK_BACK_SPACE) {
            segundaParteCuit.setFocusable(true);
            segundaParteCuit.requestFocusInWindow();
        }
    }//GEN-LAST:event_primeraParteCuitKeyReleased

    private void segundaParteCuitKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_segundaParteCuitKeyReleased
        String texto = segundaParteCuit.getText();
        if (evt.getKeyCode() != KeyEvent.VK_BACK_SPACE && texto.length() == 8) {
            terceraParteCuit.setFocusable(true);
            terceraParteCuit.requestFocusInWindow();
        }
    }//GEN-LAST:event_segundaParteCuitKeyReleased

    private void jRadioButtonDNIKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jRadioButtonDNIKeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_RIGHT) {
            jRadioButtonCUIL.setSelected(true);
            if (jRadioButtonCUIL.isSelected()) {//deshabilito DNI
                primeraParteCuit.setEnabled(true);
                segundaParteCuit.setEnabled(true);
                terceraParteCuit.setEnabled(true);
                primeraParteCuit.setFocusable(true);
                primeraParteCuit.requestFocusInWindow();
                dniClientejTextField.setEnabled(false);
            }
        }
    }//GEN-LAST:event_jRadioButtonDNIKeyReleased

    private void segundaParteCuitKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_segundaParteCuitKeyPressed
        String texto = segundaParteCuit.getText();
        if (texto.length() == 0 && evt.getKeyCode() == KeyEvent.VK_BACK_SPACE) {
            primeraParteCuit.setFocusable(true);
            primeraParteCuit.requestFocusInWindow();
        }
    }//GEN-LAST:event_segundaParteCuitKeyPressed

    private void terceraParteCuitKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_terceraParteCuitKeyPressed
        String texto = terceraParteCuit.getText();
        if (evt.getKeyCode() == KeyEvent.VK_BACK_SPACE && texto.length() == 0) {
            segundaParteCuit.setFocusable(true);
            segundaParteCuit.requestFocusInWindow();

        }
    }//GEN-LAST:event_terceraParteCuitKeyPressed

    private void terceraParteCuitKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_terceraParteCuitKeyReleased
        String texto = terceraParteCuit.getText();
        if (texto.length() > 1) {
            texto = texto.substring(0, 1);
            terceraParteCuit.setText(texto);
        }
    }//GEN-LAST:event_terceraParteCuitKeyReleased

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        if (JOptionPane.showConfirmDialog(this, "El Cliente no se va a guardar, ¿Desea cerrar de todas maneras?",
                "Advertencia", JOptionPane.YES_OPTION, JOptionPane.QUESTION_MESSAGE,
                new ImageIcon(getClass().getResource("/img/important.png"))) == JOptionPane.OK_OPTION) {
            canceled = true;
            this.dispose();
        }
    }//GEN-LAST:event_formKeyPressed

    private void jComboBoxMesItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxMesItemStateChanged
        String mes = (String) jComboBoxMes.getSelectedItem();
        int dias;
        if (mes != null) {
            if (mes.equals("Febrero")) {
                dias = 28;
            } else if (mes.equals("Noviembre") || mes.equals("Abril")
                    || mes.equals("Junio") || mes.equals("Septiembre")) {
                dias = 30;
            } else {
                dias = 31;
            }
            int selectedIndex = jComboBoxDia.getSelectedIndex();
            jComboBoxDia.removeAllItems();
            for (int i = 1; i <= dias; i++) {
                jComboBoxDia.addItem(i);
            }

            if (jComboBoxDia.getItemCount() >= selectedIndex) {
                jComboBoxDia.setSelectedIndex(selectedIndex);
            }
        }
    }//GEN-LAST:event_jComboBoxMesItemStateChanged

    /**
     * Retorna si se cancelo la inserción o actualización
     * @return true si cancelo
     */
    public boolean wasCanceled() {
        return canceled;
    }
    ///variable que indica si se cancelo
    private boolean canceled = false;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField apellidoClientejTextField;
    private javax.swing.ButtonGroup buttonGroupdni_cuil;
    private javax.swing.JTextField codPostnClientejTextField;
    private javax.swing.JTextField correoClientejTextField;
    private javax.swing.JTextField direccionClientejTextField;
    private javax.swing.JTextField dniClientejTextField;
    private javax.swing.JTextField faxClientejTextField;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox jComboBoxDia;
    private javax.swing.JComboBox jComboBoxMes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButtonCUIL;
    private javax.swing.JRadioButton jRadioButtonDNI;
    private javax.swing.JTextField localidadClientejTextField;
    private javax.swing.JTextField nombreClientejTextField;
    private javax.swing.JTextField primeraParteCuit;
    private javax.swing.JComboBox provinciaComboBox;
    private javax.swing.JTextField segundaParteCuit;
    private javax.swing.JTextField telefono2ClientejTextField;
    private javax.swing.JTextField telefonoClientejTextField;
    private javax.swing.JTextField terceraParteCuit;
    // End of variables declaration//GEN-END:variables

    public JPanel getjPanel1() {
        return jPanel1;
    }
}
