package agili.astock;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AStock.java
 *
 * Created on 06-jul-2009, 17:38:43
 */

import Herramientas.ValidadorCUIT;
import Utilidades.JPanelBackground;
import agili.astock.Agenda.AlertaEventoDialog;
import agili.astock.Agenda.MediadorAgenda;
import agili.astock.Agenda.VerificadorDeEventos;
import agili.astock.BD.AccesosBD;
import agili.astock.BD.Agenda.Evento;
import agili.astock.Herramientas.Configuracion;
import agili.astock.Herramientas.DatosDeConfiguracion;
import agili.astock.Utilidades.ThreadActualizador;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.jdo.PersistenceManager;
import javax.jdo.PersistenceManagerFactory;
import javax.swing.ButtonGroup;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JLabel;
import javax.swing.JMenu;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JRadioButtonMenuItem;
import javax.swing.JScrollPane;
import javax.swing.JSeparator;
import javax.swing.JTabbedPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.SwingUtilities;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import org.apache.log4j.PropertyConfigurator;

/**
 * Main class
 * @author Alvaro Gili
 */
public class AStock extends javax.swing.JFrame {

    private DatosDeConfiguracion ddc = DatosDeConfiguracion.getInstance();
    private ThreadActualizador ta;
    private static final Logger logger = Logger.getLogger("AStock");
    private AccesosBD accesosBD;

    /** 
     * Constructor
     */
    public AStock() throws ClassNotFoundException {


//        PropertyConfigurator.configure("AStocklog4j.properties");
        logger.setLevel(Level.INFO);
        logger.info("hola");
        
        initComponents();
        this.setIconImage(new ImageIcon(getClass().getResource("/img/logo_AStock_sin_fondo.png")).getImage());
        //ordeno por nombre
        TableRowSorter<TableModel> ordenaClientes = new TableRowSorter<TableModel>(clientesjTable.getModel());
        clientesjTable.setRowSorter(ordenaClientes);
        clientesjTable.getRowSorter().toggleSortOrder(0);

        TableRowSorter<TableModel> ordenaProveedores = new TableRowSorter<TableModel>(proveedoresjTable.getModel());
        proveedoresjTable.setRowSorter(ordenaProveedores);
        proveedoresjTable.getRowSorter().toggleSortOrder(0);

        TableRowSorter<TableModel> ordenaProductos = new TableRowSorter<TableModel>(productosjTable.getModel());
        productosjTable.setRowSorter(ordenaProductos);
        productosjTable.getRowSorter().toggleSortOrder(0);
        
        this.setExtendedState(AStock.MAXIMIZED_BOTH);
        jRadioButtonGeneral.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                jTabbedPane1.setSelectedIndex(jTabbedPane1.indexOfTab("General"));
            }
        });
        jRadioButtonClientes.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                jTabbedPane1.setSelectedIndex(jTabbedPane1.indexOfTab("Clientes"));
            }
        });
        jRadioButtonProductos.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                jTabbedPane1.setSelectedIndex(jTabbedPane1.indexOfTab("Productos"));
            }
        });
        jRadioButtonProveedores.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                jTabbedPane1.setSelectedIndex(jTabbedPane1.indexOfTab("Proveedores"));
            }
        });

        //////////////////////////////////////////////////////
        //arranco el thread que actualiza todo cada un cierto tiempo
        ta = ThreadActualizador.getInstance();
        ta.setParent(this);
        ta.setTiempoDeActualizacion(ddc.getTiempoDeActualizacion());
        ta.start();

        //////////// /////////////////////////////////////////

        VerificadorDeEventos verificadorDeEventos = new VerificadorDeEventos(ddc.isVerificarEventosAlInicio(), this, accesosBD);
        verificadorDeEventos.start();

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        view = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        productosjPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        productosjTable = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jButtonNuevoProducto = new javax.swing.JButton();
        jButtonEditarProducto = new javax.swing.JButton();
        jButtonBorrarProducto = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        clientesjPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jButtonNuevaEmpresa = new javax.swing.JButton();
        jButtonNuevaPersona = new javax.swing.JButton();
        editarCliente = new javax.swing.JButton();
        borrarCliente = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        personasjCheckBox = new javax.swing.JCheckBox();
        empresasjCheckBox = new javax.swing.JCheckBox();
        jScrollPane2 = new javax.swing.JScrollPane();
        clientesjTable = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        buscarClienteNombrejTextField = new javax.swing.JTextField();
        buscarClienteDNIjTextField = new javax.swing.JTextField();
        buscarClientePrimeraParteCuit = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        buscarClienteSegundaParteCuit = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        buscarClienteTerceraParteCuit = new javax.swing.JTextField();
        limpiarBusquedaClientesjButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        proveedoresjPanel = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButtonNuevoProveedor = new javax.swing.JButton();
        editarProveedor = new javax.swing.JButton();
        borrarProveedor = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        proveedoresjTable = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        buscarProveedorNombrejTextField = new javax.swing.JTextField();
        buscarProveedorPrimeraParteCuit = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        buscarProveedorSegundaParteCuit = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        buscarProveedorTerceraParteCuit = new javax.swing.JTextField();
        limpiarBusquedaProveedorjButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        generaljPanel = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jButtonVerProductos = new javax.swing.JButton();
        jButtonVerProveedores = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButtonVerClientes = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jButton10 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        menuBar = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jRadioButtonGeneral = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonProductos = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonClientes = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonProveedores = new javax.swing.JRadioButtonMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItemNewProd = new javax.swing.JMenuItem();
        jMenuItemEditProd = new javax.swing.JMenuItem();
        jMenuItemDeleteProd = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JSeparator();
        jMenu5 = new javax.swing.JMenu();
        jMenuItemNuevaPersonaCliente = new javax.swing.JMenuItem();
        jMenuItemNuevaEmpresaCliente = new javax.swing.JMenuItem();
        jMenuItemEditarCliente = new javax.swing.JMenuItem();
        jMenuItemBorrarCliente = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JSeparator();
        jMenuItemNewProv = new javax.swing.JMenuItem();
        jMenuItemEditProv = new javax.swing.JMenuItem();
        jMenuItemBorrarProveedor = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItemAgenda = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        jMenuItemGenBackup = new javax.swing.JMenuItem();
        jMenuItemRestoreBackup = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JSeparator();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenuItemAcercaDe = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("AStock");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        productosjPanel.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                productosjPanelComponentShown(evt);
            }
        });

        productosjTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nombre", "Categoría", "Precio costo", "Precio sin I.V.A.", "Precio I.V.A. incluido", "Stock disponible", "Stock mínimo", "Proveedor"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        productosjTable.setOpaque(false);
        jScrollPane1.setViewportView(productosjTable);
        productosjTable.getColumnModel().getColumn(0).setMinWidth(100);
        productosjTable.getColumnModel().getColumn(0).setPreferredWidth(100);
        productosjTable.getColumnModel().getColumn(1).setMinWidth(150);
        productosjTable.getColumnModel().getColumn(1).setPreferredWidth(150);
        productosjTable.getColumnModel().getColumn(2).setMinWidth(100);
        productosjTable.getColumnModel().getColumn(2).setPreferredWidth(100);
        productosjTable.getColumnModel().getColumn(3).setMinWidth(100);
        productosjTable.getColumnModel().getColumn(3).setPreferredWidth(100);
        productosjTable.getColumnModel().getColumn(4).setMinWidth(100);
        productosjTable.getColumnModel().getColumn(4).setPreferredWidth(100);
        productosjTable.getColumnModel().getColumn(5).setMinWidth(100);
        productosjTable.getColumnModel().getColumn(5).setPreferredWidth(100);
        productosjTable.getColumnModel().getColumn(6).setMinWidth(100);
        productosjTable.getColumnModel().getColumn(6).setPreferredWidth(100);
        productosjTable.getColumnModel().getColumn(7).setMinWidth(100);
        productosjTable.getColumnModel().getColumn(7).setPreferredWidth(100);
        productosjTable.getColumnModel().getColumn(8).setMinWidth(200);
        productosjTable.getColumnModel().getColumn(8).setPreferredWidth(200);

        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel5.setPreferredSize(new java.awt.Dimension(943, 60));

        jButtonNuevoProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("./agili/astock/img/ark.png"))); // NOI18N
        jButtonNuevoProducto.setText("Agregar Producto");

        jButtonEditarProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("./agili/astock/img/document-edit.png"))); // NOI18N
        jButtonEditarProducto.setText("Editar");

        jButtonBorrarProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("./agili/astock/img/list-remove.png"))); // NOI18N
        jButtonBorrarProducto.setText("Borrar");

        jButton4.setText("Agregar categoria");

        jButton5.setText("Borrar categoria");

        org.jdesktop.layout.GroupLayout jPanel5Layout = new org.jdesktop.layout.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .add(jButtonNuevoProducto)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jButtonEditarProducto)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jButtonBorrarProducto)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 168, Short.MAX_VALUE)
                .add(jButton4)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jButton5)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(jPanel5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jButtonNuevoProducto)
                    .add(jButtonEditarProducto)
                    .add(jButtonBorrarProducto)
                    .add(jButton5)
                    .add(jButton4))
                .addContainerGap())
        );

        org.jdesktop.layout.GroupLayout productosjPanelLayout = new org.jdesktop.layout.GroupLayout(productosjPanel);
        productosjPanel.setLayout(productosjPanelLayout);
        productosjPanelLayout.setHorizontalGroup(
            productosjPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, productosjPanelLayout.createSequentialGroup()
                .add(productosjPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, productosjPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 918, Short.MAX_VALUE))
                    .add(productosjPanelLayout.createSequentialGroup()
                        .add(10, 10, 10)
                        .add(jPanel5, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 920, Short.MAX_VALUE)))
                .addContainerGap())
        );
        productosjPanelLayout.setVerticalGroup(
            productosjPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(productosjPanelLayout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 352, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(333, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Productos", new javax.swing.ImageIcon(getClass().getResource("/img/caja22x22.gif")), productosjPanel); // NOI18N

        clientesjPanel.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                clientesjPanelComponentShown(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jButtonNuevaEmpresa.setIcon(new javax.swing.ImageIcon(getClass().getResource("./agili/astock/img/user-group-new.png"))); // NOI18N
        jButtonNuevaEmpresa.setText("Nueva Empresa");
        jButtonNuevaEmpresa.setToolTipText("Responsable Inscripto o Empresa");

        jButtonNuevaPersona.setIcon(new javax.swing.ImageIcon(getClass().getResource("./agili/astock/img/list-add-user.png"))); // NOI18N
        jButtonNuevaPersona.setText("Nueva Persona");

        editarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("./agili/astock/img/document-edit.png"))); // NOI18N
        editarCliente.setText("Editar");

        borrarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("./agili/astock/img/list-remove.png"))); // NOI18N
        borrarCliente.setText("Borrar");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/display.png"))); // NOI18N
        jLabel2.setText("Mostrar:");

        personasjCheckBox.setSelected(true);
        personasjCheckBox.setText("Personas");
        personasjCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                personasjCheckBoxActionPerformed(evt);
            }
        });

        empresasjCheckBox.setSelected(true);
        empresasjCheckBox.setText("Empresas");
        empresasjCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                personasjCheckBoxActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jButtonNuevaPersona)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jButtonNuevaEmpresa)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(editarCliente)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(borrarCliente)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 54, Short.MAX_VALUE)
                .add(jLabel2)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(personasjCheckBox)
                .add(18, 18, 18)
                .add(empresasjCheckBox)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jButtonNuevaPersona)
                    .add(jButtonNuevaEmpresa)
                    .add(editarCliente)
                    .add(borrarCliente)
                    .add(empresasjCheckBox)
                    .add(personasjCheckBox)
                    .add(jLabel2))
                .addContainerGap())
        );

        jScrollPane2.setOpaque(false);

        clientesjTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "DNI / CUIT", "Dirección", "Código Postal", "Localidad", "Provincia", "Teléfono", "Tel. Alternativo", "E-mail", "Fax", "Cumpleaños", "Tipo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        clientesjTable.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        clientesjTable.setMinimumSize(new java.awt.Dimension(1250, 0));
        clientesjTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        clientesjTable.getTableHeader().setReorderingAllowed(false);
        clientesjTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clientesjTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(clientesjTable);
        clientesjTable.getColumnModel().getColumn(0).setMinWidth(200);
        clientesjTable.getColumnModel().getColumn(0).setPreferredWidth(200);
        clientesjTable.getColumnModel().getColumn(1).setMinWidth(100);
        clientesjTable.getColumnModel().getColumn(1).setPreferredWidth(100);
        clientesjTable.getColumnModel().getColumn(2).setMinWidth(200);
        clientesjTable.getColumnModel().getColumn(2).setPreferredWidth(200);
        clientesjTable.getColumnModel().getColumn(3).setMinWidth(100);
        clientesjTable.getColumnModel().getColumn(3).setPreferredWidth(100);
        clientesjTable.getColumnModel().getColumn(4).setMinWidth(100);
        clientesjTable.getColumnModel().getColumn(4).setPreferredWidth(100);
        clientesjTable.getColumnModel().getColumn(5).setMinWidth(100);
        clientesjTable.getColumnModel().getColumn(5).setPreferredWidth(100);
        clientesjTable.getColumnModel().getColumn(6).setMinWidth(100);
        clientesjTable.getColumnModel().getColumn(6).setPreferredWidth(100);
        clientesjTable.getColumnModel().getColumn(7).setMinWidth(100);
        clientesjTable.getColumnModel().getColumn(7).setPreferredWidth(100);
        clientesjTable.getColumnModel().getColumn(8).setMinWidth(150);
        clientesjTable.getColumnModel().getColumn(8).setPreferredWidth(150);
        clientesjTable.getColumnModel().getColumn(9).setMinWidth(100);
        clientesjTable.getColumnModel().getColumn(9).setPreferredWidth(100);
        clientesjTable.getColumnModel().getColumn(10).setMinWidth(100);
        clientesjTable.getColumnModel().getColumn(10).setPreferredWidth(100);
        clientesjTable.getColumnModel().getColumn(11).setMinWidth(100);
        clientesjTable.getColumnModel().getColumn(11).setPreferredWidth(100);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Búsquedas"));

        buscarClienteNombrejTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        buscarClienteDNIjTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        buscarClientePrimeraParteCuit.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        buscarClientePrimeraParteCuit.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                buscarClientePrimeraParteCuitKeyReleased(evt);
            }
        });

        jLabel12.setText(" - ");

        buscarClienteSegundaParteCuit.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        buscarClienteSegundaParteCuit.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                buscarClienteSegundaParteCuitKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                buscarClienteSegundaParteCuitKeyReleased(evt);
            }
        });

        jLabel13.setText(" - ");

        buscarClienteTerceraParteCuit.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        buscarClienteTerceraParteCuit.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                buscarClienteTerceraParteCuitKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                buscarClienteTerceraParteCuitKeyReleased(evt);
            }
        });

        limpiarBusquedaClientesjButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/mail-mark-junk.png"))); // NOI18N
        limpiarBusquedaClientesjButton.setText("Limpiar Búsqueda");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/page-zoom.png"))); // NOI18N

        jLabel4.setText("Buscar por Nombre:");

        jLabel5.setText("Buscar por DNI:");

        jLabel6.setText("Buscar por CUIL / CUIT:");

        org.jdesktop.layout.GroupLayout jPanel3Layout = new org.jdesktop.layout.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel3Layout.createSequentialGroup()
                .add(21, 21, 21)
                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(buscarClienteNombrejTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 120, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel4))
                .add(38, 38, 38)
                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(buscarClienteDNIjTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 120, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel5))
                .add(41, 41, 41)
                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel3Layout.createSequentialGroup()
                        .add(jLabel6)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(jLabel1))
                    .add(jPanel3Layout.createSequentialGroup()
                        .add(buscarClientePrimeraParteCuit, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 22, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jLabel12)
                        .add(5, 5, 5)
                        .add(buscarClienteSegundaParteCuit, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 90, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(5, 5, 5)
                        .add(jLabel13)
                        .add(5, 5, 5)
                        .add(buscarClienteTerceraParteCuit, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(14, 14, 14)
                        .add(limpiarBusquedaClientesjButton)))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel3Layout.createSequentialGroup()
                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                        .add(jLabel4)
                        .add(jLabel5)
                        .add(jLabel6))
                    .add(jLabel1))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(buscarClienteDNIjTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(buscarClienteNombrejTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(buscarClientePrimeraParteCuit, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(limpiarBusquedaClientesjButton)
                    .add(buscarClienteSegundaParteCuit, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel13)
                    .add(buscarClienteTerceraParteCuit, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel12))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        org.jdesktop.layout.GroupLayout clientesjPanelLayout = new org.jdesktop.layout.GroupLayout(clientesjPanel);
        clientesjPanel.setLayout(clientesjPanelLayout);
        clientesjPanelLayout.setHorizontalGroup(
            clientesjPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, clientesjPanelLayout.createSequentialGroup()
                .addContainerGap()
                .add(clientesjPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jScrollPane2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 922, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jPanel3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        clientesjPanelLayout.setVerticalGroup(
            clientesjPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(clientesjPanelLayout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jScrollPane2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 584, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jScrollPane2.getAccessibleContext().setAccessibleParent(jScrollPane2);

        jTabbedPane1.addTab("Clientes", new javax.swing.ImageIcon(getClass().getResource("/img/clientes22x22.png")), clientesjPanel); // NOI18N

        proveedoresjPanel.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                proveedoresjPanelComponentShown(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jButtonNuevoProveedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("./agili/astock/img/camion24.png"))); // NOI18N
        jButtonNuevoProveedor.setText("Nuevo Proveedor");

        editarProveedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("./agili/astock/img/document-edit.png"))); // NOI18N
        editarProveedor.setText("Editar");

        borrarProveedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("./agili/astock/img/list-remove.png"))); // NOI18N
        borrarProveedor.setText("Borrar");

        org.jdesktop.layout.GroupLayout jPanel2Layout = new org.jdesktop.layout.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .add(jButtonNuevoProveedor)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(editarProveedor)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(borrarProveedor)
                .addContainerGap(500, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jButtonNuevoProveedor)
                    .add(editarProveedor)
                    .add(borrarProveedor))
                .addContainerGap())
        );

        jScrollPane3.setAutoscrolls(true);
        jScrollPane3.setOpaque(false);

        proveedoresjTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "CUIT", "Dirección", "Código Postal", "Localidad", "Provincia", "Teléfono", "Tel. Alternativo", "E-mail", "Fax"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        proveedoresjTable.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        proveedoresjTable.setMinimumSize(new java.awt.Dimension(1250, 0));
        proveedoresjTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        proveedoresjTable.getTableHeader().setReorderingAllowed(false);
        proveedoresjTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                proveedoresjTableMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(proveedoresjTable);
        proveedoresjTable.getColumnModel().getColumn(0).setMinWidth(200);
        proveedoresjTable.getColumnModel().getColumn(0).setPreferredWidth(200);
        proveedoresjTable.getColumnModel().getColumn(1).setMinWidth(100);
        proveedoresjTable.getColumnModel().getColumn(1).setPreferredWidth(100);
        proveedoresjTable.getColumnModel().getColumn(2).setMinWidth(200);
        proveedoresjTable.getColumnModel().getColumn(2).setPreferredWidth(200);
        proveedoresjTable.getColumnModel().getColumn(3).setMinWidth(100);
        proveedoresjTable.getColumnModel().getColumn(3).setPreferredWidth(100);
        proveedoresjTable.getColumnModel().getColumn(4).setMinWidth(100);
        proveedoresjTable.getColumnModel().getColumn(4).setPreferredWidth(100);
        proveedoresjTable.getColumnModel().getColumn(5).setMinWidth(100);
        proveedoresjTable.getColumnModel().getColumn(5).setPreferredWidth(100);
        proveedoresjTable.getColumnModel().getColumn(6).setMinWidth(100);
        proveedoresjTable.getColumnModel().getColumn(6).setPreferredWidth(100);
        proveedoresjTable.getColumnModel().getColumn(7).setMinWidth(100);
        proveedoresjTable.getColumnModel().getColumn(7).setPreferredWidth(100);
        proveedoresjTable.getColumnModel().getColumn(8).setMinWidth(150);
        proveedoresjTable.getColumnModel().getColumn(8).setPreferredWidth(150);
        proveedoresjTable.getColumnModel().getColumn(9).setMinWidth(100);
        proveedoresjTable.getColumnModel().getColumn(9).setPreferredWidth(100);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Búsquedas"));

        buscarProveedorNombrejTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        buscarProveedorPrimeraParteCuit.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        buscarProveedorPrimeraParteCuit.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                buscarProveedorPrimeraParteCuitKeyReleased(evt);
            }
        });

        jLabel14.setText(" - ");

        buscarProveedorSegundaParteCuit.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        buscarProveedorSegundaParteCuit.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                buscarProveedorSegundaParteCuitKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                buscarProveedorSegundaParteCuitKeyReleased(evt);
            }
        });

        jLabel15.setText(" - ");

        buscarProveedorTerceraParteCuit.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        buscarProveedorTerceraParteCuit.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                buscarProveedorTerceraParteCuitKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                buscarProveedorTerceraParteCuitKeyReleased(evt);
            }
        });

        limpiarBusquedaProveedorjButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/mail-mark-junk.png"))); // NOI18N
        limpiarBusquedaProveedorjButton.setText("Limpiar Búsqueda");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/page-zoom.png"))); // NOI18N

        jLabel7.setText("Buscar por Nombre:");

        jLabel8.setText("Buscar por CUIL / CUIT:");

        org.jdesktop.layout.GroupLayout jPanel4Layout = new org.jdesktop.layout.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel4Layout.createSequentialGroup()
                .add(21, 21, 21)
                .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(buscarProveedorNombrejTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 120, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel7))
                .add(39, 39, 39)
                .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel4Layout.createSequentialGroup()
                        .add(buscarProveedorPrimeraParteCuit, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 25, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(5, 5, 5)
                        .add(jLabel14)
                        .add(5, 5, 5)
                        .add(buscarProveedorSegundaParteCuit, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 90, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(5, 5, 5)
                        .add(jLabel15)
                        .add(5, 5, 5)
                        .add(buscarProveedorTerceraParteCuit, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(jLabel8))
                .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(jPanel4Layout.createSequentialGroup()
                        .add(18, 18, 18)
                        .add(limpiarBusquedaProveedorjButton)
                        .addContainerGap())
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(jLabel3)
                        .add(18, 18, 18))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel4Layout.createSequentialGroup()
                .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                        .add(jLabel7)
                        .add(jLabel8))
                    .add(jLabel3))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(buscarProveedorNombrejTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(buscarProveedorPrimeraParteCuit, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(buscarProveedorSegundaParteCuit, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel15)
                    .add(buscarProveedorTerceraParteCuit, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel14)
                    .add(limpiarBusquedaProveedorjButton))
                .add(34, 34, 34))
        );

        org.jdesktop.layout.GroupLayout proveedoresjPanelLayout = new org.jdesktop.layout.GroupLayout(proveedoresjPanel);
        proveedoresjPanel.setLayout(proveedoresjPanelLayout);
        proveedoresjPanelLayout.setHorizontalGroup(
            proveedoresjPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, proveedoresjPanelLayout.createSequentialGroup()
                .addContainerGap()
                .add(proveedoresjPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jScrollPane3, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 918, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jPanel4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jPanel2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        proveedoresjPanelLayout.setVerticalGroup(
            proveedoresjPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(proveedoresjPanelLayout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jScrollPane3, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 570, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 95, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Proveedores", new javax.swing.ImageIcon(getClass().getResource("/img/proveedores22x22.png")), proveedoresjPanel); // NOI18N

        generaljPanel.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                generaljPanelComponentShown(evt);
            }
        });

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Accesos Rápidos"));
        jPanel6.setOpaque(false);

        jButtonVerProductos.setIcon(new javax.swing.ImageIcon(getClass().getResource("./agili/astock/img/caja.gif"))); // NOI18N
        jButtonVerProductos.setText("Ver productos");
        jButtonVerProductos.setPreferredSize(new java.awt.Dimension(157, 59));
        jButtonVerProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVerProductosActionPerformed(evt);
            }
        });

        jButtonVerProveedores.setIcon(new javax.swing.ImageIcon(getClass().getResource("./agili/astock/img/proveedores.png"))); // NOI18N
        jButtonVerProveedores.setText("Ver proveedores");
        jButtonVerProveedores.setPreferredSize(new java.awt.Dimension(157, 59));
        jButtonVerProveedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVerProveedoresActionPerformed(evt);
            }
        });

        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("./agili/astock/img/date48.png"))); // NOI18N
        jButton9.setText("Agenda");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButtonVerClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("./agili/astock/img/clientes.png"))); // NOI18N
        jButtonVerClientes.setText("Ver clientes");
        jButtonVerClientes.setPreferredSize(new java.awt.Dimension(157, 59));
        jButtonVerClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVerClientesActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel6Layout = new org.jdesktop.layout.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel6Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(jButtonVerProductos, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
                    .add(jButtonVerProveedores, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jPanel6Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jButtonVerClientes, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)
                    .add(jButton9, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel6Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(jButtonVerProductos, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                    .add(jButtonVerClientes, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18)
                .add(jPanel6Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jButtonVerProveedores, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(jButton9, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("Mantenimiento y configuración"));
        jPanel7.setOpaque(false);

        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("./agili/astock/img/agt_utilities48.png"))); // NOI18N
        jButton10.setText("Configuración");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("./agili/astock/img/carrito48.png"))); // NOI18N
        jButton7.setText("Ver productos a reponer");
        jButton7.setEnabled(false);

        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("./agili/astock/img/lists.png"))); // NOI18N
        jButton8.setText("Pedido a proveedor");
        jButton8.setEnabled(false);

        jButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("./agili/astock/img/klipper.png"))); // NOI18N
        jButton11.setText("Lista de mails de clientes");
        jButton11.setEnabled(false);

        jButton12.setIcon(new javax.swing.ImageIcon(getClass().getResource("./agili/astock/img/klipper.png"))); // NOI18N
        jButton12.setText("Lista de mails de proveedores");
        jButton12.setEnabled(false);

        jButton13.setIcon(new javax.swing.ImageIcon(getClass().getResource("./agili/astock/img/EntradaStock.png"))); // NOI18N
        jButton13.setText("Entrada de Stock");
        jButton13.setEnabled(false);

        org.jdesktop.layout.GroupLayout jPanel7Layout = new org.jdesktop.layout.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel7Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jButton7, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jButton12, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jButton11, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jButton10, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jButton13, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(jButton8, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .add(jButton7, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 59, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(18, 18, 18)
                .add(jButton8)
                .add(18, 18, 18)
                .add(jButton13, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 56, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(18, 18, 18)
                .add(jButton10)
                .add(18, 18, 18)
                .add(jButton11)
                .add(18, 18, 18)
                .add(jButton12)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder("Facturación y pedidos"));
        jPanel8.setOpaque(false);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("./agili/astock/img/carritoPedGenerado.png"))); // NOI18N
        jButton2.setText("Nueva compra");
        jButton2.setEnabled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("./agili/astock/img/factura.png"))); // NOI18N
        jButton1.setText("Nueva factura");

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("./agili/astock/img/carritos.png"))); // NOI18N
        jButton3.setText("Compras generadas");
        jButton3.setEnabled(false);

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("./agili/astock/img/presupuesto.png"))); // NOI18N
        jButton6.setText("Nuevo presupuesto");
        jButton6.setEnabled(false);

        org.jdesktop.layout.GroupLayout jPanel8Layout = new org.jdesktop.layout.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel8Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jButton1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)
                    .add(jButton3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jPanel8Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(jButton6, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(jButton2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel8Layout.createSequentialGroup()
                .add(11, 11, 11)
                .add(jPanel8Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jButton1)
                    .add(jButton2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 58, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18)
                .add(jPanel8Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jButton3)
                    .add(jButton6, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        org.jdesktop.layout.GroupLayout generaljPanelLayout = new org.jdesktop.layout.GroupLayout(generaljPanel);
        generaljPanel.setLayout(generaljPanelLayout);
        generaljPanelLayout.setHorizontalGroup(
            generaljPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(generaljPanelLayout.createSequentialGroup()
                .add(27, 27, 27)
                .add(generaljPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(jPanel6, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jPanel8, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18)
                .add(jPanel7, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(93, Short.MAX_VALUE))
        );
        generaljPanelLayout.setVerticalGroup(
            generaljPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(generaljPanelLayout.createSequentialGroup()
                .add(11, 11, 11)
                .add(generaljPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel7, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(generaljPanelLayout.createSequentialGroup()
                        .add(jPanel6, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(11, 11, 11)
                        .add(jPanel8, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(266, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("General", new javax.swing.ImageIcon(getClass().getResource("/img/home.png")), generaljPanel); // NOI18N

        jMenu1.setText("Archivo");
        jMenu1.setToolTipText("");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("./agili/astock/img/exit.png"))); // NOI18N
        jMenuItem1.setText("Salir");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        menuBar.add(jMenu1);

        jMenu3.setText("Ver");

        jRadioButtonGeneral.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, java.awt.event.InputEvent.ALT_MASK));
        view.add(jRadioButtonGeneral);
        jRadioButtonGeneral.setSelected(true);
        jRadioButtonGeneral.setText("General");
        jMenu3.add(jRadioButtonGeneral);

        jRadioButtonProductos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.ALT_MASK));
        view.add(jRadioButtonProductos);
        jRadioButtonProductos.setText("Productos");
        jMenu3.add(jRadioButtonProductos);

        jRadioButtonClientes.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_MASK));
        view.add(jRadioButtonClientes);
        jRadioButtonClientes.setText("Clientes");
        jMenu3.add(jRadioButtonClientes);

        jRadioButtonProveedores.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.ALT_MASK));
        view.add(jRadioButtonProveedores);
        jRadioButtonProveedores.setText("Proveedores");
        jMenu3.add(jRadioButtonProveedores);

        menuBar.add(jMenu3);

        jMenu2.setText("Administración");

        jMenuItemNewProd.setIcon(new javax.swing.ImageIcon(getClass().getResource("./agili/astock/img/ark.png"))); // NOI18N
        jMenuItemNewProd.setText("Nuevo Producto");
        jMenu2.add(jMenuItemNewProd);

        jMenuItemEditProd.setIcon(new javax.swing.ImageIcon(getClass().getResource("./agili/astock/img/document-edit.png"))); // NOI18N
        jMenuItemEditProd.setText("Editar Producto");
        jMenu2.add(jMenuItemEditProd);

        jMenuItemDeleteProd.setIcon(new javax.swing.ImageIcon(getClass().getResource("./agili/astock/img/list-remove.png"))); // NOI18N
        jMenuItemDeleteProd.setText("Borrar Producto");
        jMenu2.add(jMenuItemDeleteProd);
        jMenu2.add(jSeparator1);

        jMenu5.setIcon(new javax.swing.ImageIcon(getClass().getResource("./agili/astock/img/list-add-user.png"))); // NOI18N
        jMenu5.setText("Nuevo Cliente");

        jMenuItemNuevaPersonaCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("./agili/astock/img/list-add-user.png"))); // NOI18N
        jMenuItemNuevaPersonaCliente.setText("Persona");
        jMenu5.add(jMenuItemNuevaPersonaCliente);

        jMenuItemNuevaEmpresaCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("./agili/astock/img/user-group-new.png"))); // NOI18N
        jMenuItemNuevaEmpresaCliente.setText("Empresa");
        jMenu5.add(jMenuItemNuevaEmpresaCliente);

        jMenu2.add(jMenu5);

        jMenuItemEditarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("./agili/astock/img/document-edit.png"))); // NOI18N
        jMenuItemEditarCliente.setText("Editar Cliente");
        jMenu2.add(jMenuItemEditarCliente);

        jMenuItemBorrarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("./agili/astock/img/list-remove.png"))); // NOI18N
        jMenuItemBorrarCliente.setText("Borrar Cliente");
        jMenu2.add(jMenuItemBorrarCliente);
        jMenu2.add(jSeparator2);

        jMenuItemNewProv.setIcon(new javax.swing.ImageIcon(getClass().getResource("./agili/astock/img/camion24.png"))); // NOI18N
        jMenuItemNewProv.setText("Nuevo Proveedor");
        jMenu2.add(jMenuItemNewProv);

        jMenuItemEditProv.setIcon(new javax.swing.ImageIcon(getClass().getResource("./agili/astock/img/document-edit.png"))); // NOI18N
        jMenuItemEditProv.setText("Editar Proveedor");
        jMenu2.add(jMenuItemEditProv);

        jMenuItemBorrarProveedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("./agili/astock/img/list-remove.png"))); // NOI18N
        jMenuItemBorrarProveedor.setText("Borrar Proveedor");
        jMenu2.add(jMenuItemBorrarProveedor);

        menuBar.add(jMenu2);

        jMenu4.setText("Herramientas");

        jMenuItemAgenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("./agili/astock/img/date.png"))); // NOI18N
        jMenuItemAgenda.setText("Agenda");
        jMenuItemAgenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAgendaActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItemAgenda);

        jMenuItem2.setText("Calculador CUIT");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem2);
        jMenu4.add(jSeparator4);

        jMenuItemGenBackup.setIcon(new javax.swing.ImageIcon(getClass().getResource("./agili/astock/img/backupBD.png"))); // NOI18N
        jMenuItemGenBackup.setText("Generar backup de la base de datos");
        jMenu4.add(jMenuItemGenBackup);

        jMenuItemRestoreBackup.setIcon(new javax.swing.ImageIcon(getClass().getResource("./agili/astock/img/restorebd.png"))); // NOI18N
        jMenuItemRestoreBackup.setText("Restaurar backup de la base de datos");
        jMenu4.add(jMenuItemRestoreBackup);
        jMenu4.add(jSeparator3);

        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("./agili/astock/img/agt_utilities32.png"))); // NOI18N
        jMenuItem3.setText("Configuración");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem3);

        menuBar.add(jMenu4);

        jMenu6.setText("Ayuda");

        jMenuItemAcercaDe.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_SPACE, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemAcercaDe.setIcon(new javax.swing.ImageIcon(getClass().getResource("./agili/astock/img/logo_AStock_sin_fondo32.png"))); // NOI18N
        jMenuItemAcercaDe.setText("Acerca de AStock");
        jMenuItemAcercaDe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAcercaDeActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItemAcercaDe);

        menuBar.add(jMenu6);

        setJMenuBar(menuBar);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .add(jTabbedPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 947, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jTabbedPane1))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Cierra la aplicacion
     */
    private void close() {
        if (JOptionPane.showConfirmDialog(this, "¿Realmente desea cerrar AStock?",
                "Confirmación", JOptionPane.OK_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE,
                new ImageIcon(getClass().getResource("/img/svn_status.png"))) == JOptionPane.OK_OPTION) {
            try {
                persistenceManager.close();
            } catch (Exception e) {
            }

            System.exit(0);
        }
    }
    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        close();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        close();
    }//GEN-LAST:event_formWindowClosing

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        //Selecciono el menú
        if (evt.isAltDown()) {
            /*menuBar.getMenu(0).setSelected(true);
            if(evt.getKeyCode() == KeyEvent.VK_A)
            menuBar.getMenu(0).show();*/
            System.out.println("implementar despliegue menú");
        }
    }//GEN-LAST:event_formKeyPressed

    private void personasjCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_personasjCheckBoxActionPerformed
        ta.actualizarClientes();
        buscarClienteNombrejTextField.setText("");
        buscarClienteDNIjTextField.setText("");
        buscarClientePrimeraParteCuit.setText("");
        buscarClienteSegundaParteCuit.setText("");
        buscarClienteTerceraParteCuit.setText("");
    }//GEN-LAST:event_personasjCheckBoxActionPerformed

    private void clientesjTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clientesjTableMouseClicked

        editarCliente.setEnabled(true);
        borrarCliente.setEnabled(true);
        jMenuItemBorrarCliente.setEnabled(true);
        jMenuItemEditarCliente.setEnabled(true);
    }//GEN-LAST:event_clientesjTableMouseClicked

    private void proveedoresjPanelComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_proveedoresjPanelComponentShown
        jRadioButtonProveedores.setSelected(true);
    }//GEN-LAST:event_proveedoresjPanelComponentShown

    private void clientesjPanelComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_clientesjPanelComponentShown
        jRadioButtonClientes.setSelected(true);
    }//GEN-LAST:event_clientesjPanelComponentShown

    private void productosjPanelComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_productosjPanelComponentShown
        jRadioButtonProductos.setSelected(true);
    }//GEN-LAST:event_productosjPanelComponentShown

    private void jMenuItemAcercaDeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAcercaDeActionPerformed
        AcercaDe acercaDe = new AcercaDe(this, true);
        acercaDe.setLocationRelativeTo(this);
        acercaDe.setVisible(true);
    }//GEN-LAST:event_jMenuItemAcercaDeActionPerformed

    private void buscarClientePrimeraParteCuitKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_buscarClientePrimeraParteCuitKeyReleased
        String texto = buscarClientePrimeraParteCuit.getText();
        if (texto.length() == 2 && evt.getKeyCode() != KeyEvent.VK_BACK_SPACE) {
            buscarClienteSegundaParteCuit.setFocusable(true);
            buscarClienteSegundaParteCuit.requestFocusInWindow();
        }
}//GEN-LAST:event_buscarClientePrimeraParteCuitKeyReleased

    private void buscarClienteSegundaParteCuitKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_buscarClienteSegundaParteCuitKeyReleased
        String texto = buscarClienteSegundaParteCuit.getText();
        if (texto.length() == 8 && evt.getKeyCode() != KeyEvent.VK_BACK_SPACE) {
            buscarClienteTerceraParteCuit.setFocusable(true);
            buscarClienteTerceraParteCuit.requestFocusInWindow();
        }

}//GEN-LAST:event_buscarClienteSegundaParteCuitKeyReleased

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed

        ValidadorCUIT validadorCUIT = new ValidadorCUIT();
        int s = validadorCUIT.generarUltimoNumero(JOptionPane.showInputDialog(this, "Ingrese CUIT de la siguiente forma: 20-29494566"));
        JOptionPane.showMessageDialog(this, s);

    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void proveedoresjTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_proveedoresjTableMouseClicked
        editarProveedor.setEnabled(true);
        borrarProveedor.setEnabled(true);
        jMenuItemBorrarProveedor.setEnabled(true);
        jMenuItemEditProv.setEnabled(true);
    }//GEN-LAST:event_proveedoresjTableMouseClicked

    private void buscarProveedorPrimeraParteCuitKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_buscarProveedorPrimeraParteCuitKeyReleased
        String texto = buscarProveedorPrimeraParteCuit.getText();
        if (texto.length() == 2 && evt.getKeyCode() != KeyEvent.VK_BACK_SPACE) {
            buscarProveedorSegundaParteCuit.setFocusable(true);
            buscarProveedorSegundaParteCuit.requestFocusInWindow();
        }
    }//GEN-LAST:event_buscarProveedorPrimeraParteCuitKeyReleased

    private void buscarProveedorSegundaParteCuitKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_buscarProveedorSegundaParteCuitKeyReleased
        String texto = buscarProveedorSegundaParteCuit.getText();
        if (texto.length() == 8 && evt.getKeyCode() != KeyEvent.VK_BACK_SPACE) {
            buscarProveedorTerceraParteCuit.setFocusable(true);
            buscarProveedorTerceraParteCuit.requestFocusInWindow();
        }
    }//GEN-LAST:event_buscarProveedorSegundaParteCuitKeyReleased

    private void buscarProveedorTerceraParteCuitKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_buscarProveedorTerceraParteCuitKeyReleased
        String texto = buscarProveedorTerceraParteCuit.getText();
        if (texto.length() > 1) {
            texto = texto.substring(0, 1);
            buscarProveedorTerceraParteCuit.setText(texto);
        }
    }//GEN-LAST:event_buscarProveedorTerceraParteCuitKeyReleased

    private void buscarClienteSegundaParteCuitKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_buscarClienteSegundaParteCuitKeyPressed
        String texto = buscarClienteSegundaParteCuit.getText();
        if (texto.length() == 0 && evt.getKeyCode() == KeyEvent.VK_BACK_SPACE) {
            buscarClientePrimeraParteCuit.setFocusable(true);
            buscarClientePrimeraParteCuit.requestFocusInWindow();
        }
    }//GEN-LAST:event_buscarClienteSegundaParteCuitKeyPressed

    private void buscarClienteTerceraParteCuitKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_buscarClienteTerceraParteCuitKeyPressed
        String texto = buscarClienteTerceraParteCuit.getText();
        if (evt.getKeyCode() == KeyEvent.VK_BACK_SPACE && texto.length() == 0) {
            buscarClienteSegundaParteCuit.setFocusable(true);
            buscarClienteSegundaParteCuit.requestFocusInWindow();
        }
    }//GEN-LAST:event_buscarClienteTerceraParteCuitKeyPressed

    private void buscarProveedorSegundaParteCuitKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_buscarProveedorSegundaParteCuitKeyPressed
        String texto = buscarProveedorSegundaParteCuit.getText();
        if (texto.length() == 0 && evt.getKeyCode() == KeyEvent.VK_BACK_SPACE) {
            buscarProveedorPrimeraParteCuit.setFocusable(true);
            buscarProveedorPrimeraParteCuit.requestFocusInWindow();
        }
    }//GEN-LAST:event_buscarProveedorSegundaParteCuitKeyPressed

    private void buscarClienteTerceraParteCuitKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_buscarClienteTerceraParteCuitKeyReleased
        String texto = buscarClienteTerceraParteCuit.getText();
        if (texto.length() > 1) {
            texto = texto.substring(0, 1);
            buscarClienteTerceraParteCuit.setText(texto);
        }
    }//GEN-LAST:event_buscarClienteTerceraParteCuitKeyReleased

    private void buscarProveedorTerceraParteCuitKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_buscarProveedorTerceraParteCuitKeyPressed
        String texto = buscarProveedorTerceraParteCuit.getText();
        if (evt.getKeyCode() == KeyEvent.VK_BACK_SPACE && texto.length() == 0) {
            buscarProveedorSegundaParteCuit.setFocusable(true);
            buscarProveedorSegundaParteCuit.requestFocusInWindow();
        }
    }//GEN-LAST:event_buscarProveedorTerceraParteCuitKeyPressed

    private void jMenuItemAgendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAgendaActionPerformed

        MediadorAgenda agenda = MediadorAgenda.getInstance();
    }//GEN-LAST:event_jMenuItemAgendaActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
    }//GEN-LAST:event_formWindowOpened

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        Configuracion configuracion = new Configuracion(this, true, conexion, persistenceManager);
        configuracion.setLocationRelativeTo(this);
        configuracion.setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jButtonVerProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVerProductosActionPerformed
        jTabbedPane1.setSelectedIndex(jTabbedPane1.indexOfTab("Productos"));
    }//GEN-LAST:event_jButtonVerProductosActionPerformed

    private void jButtonVerClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVerClientesActionPerformed
        jTabbedPane1.setSelectedIndex(jTabbedPane1.indexOfTab("Clientes"));
    }//GEN-LAST:event_jButtonVerClientesActionPerformed

    private void jButtonVerProveedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVerProveedoresActionPerformed
        jTabbedPane1.setSelectedIndex(jTabbedPane1.indexOfTab("Proveedores"));
    }//GEN-LAST:event_jButtonVerProveedoresActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        MediadorAgenda agenda = MediadorAgenda.getInstance();
    }//GEN-LAST:event_jButton9ActionPerformed

    private void generaljPanelComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_generaljPanelComponentShown
        jRadioButtonGeneral.setSelected(true);
    }//GEN-LAST:event_generaljPanelComponentShown

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed
    private PersistenceManagerFactory conexion;
    private PersistenceManager persistenceManager;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton borrarCliente;
    private javax.swing.JButton borrarProveedor;
    private javax.swing.JTextField buscarClienteDNIjTextField;
    private javax.swing.JTextField buscarClienteNombrejTextField;
    private javax.swing.JTextField buscarClientePrimeraParteCuit;
    private javax.swing.JTextField buscarClienteSegundaParteCuit;
    private javax.swing.JTextField buscarClienteTerceraParteCuit;
    private javax.swing.JTextField buscarProveedorNombrejTextField;
    private javax.swing.JTextField buscarProveedorPrimeraParteCuit;
    private javax.swing.JTextField buscarProveedorSegundaParteCuit;
    private javax.swing.JTextField buscarProveedorTerceraParteCuit;
    private javax.swing.JPanel clientesjPanel;
    private javax.swing.JTable clientesjTable;
    private javax.swing.JButton editarCliente;
    private javax.swing.JButton editarProveedor;
    private javax.swing.JCheckBox empresasjCheckBox;
    private javax.swing.JPanel generaljPanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JButton jButtonBorrarProducto;
    private javax.swing.JButton jButtonEditarProducto;
    private javax.swing.JButton jButtonNuevaEmpresa;
    private javax.swing.JButton jButtonNuevaPersona;
    private javax.swing.JButton jButtonNuevoProducto;
    private javax.swing.JButton jButtonNuevoProveedor;
    private javax.swing.JButton jButtonVerClientes;
    private javax.swing.JButton jButtonVerProductos;
    private javax.swing.JButton jButtonVerProveedores;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItemAcercaDe;
    private javax.swing.JMenuItem jMenuItemAgenda;
    private javax.swing.JMenuItem jMenuItemBorrarCliente;
    private javax.swing.JMenuItem jMenuItemBorrarProveedor;
    private javax.swing.JMenuItem jMenuItemDeleteProd;
    private javax.swing.JMenuItem jMenuItemEditProd;
    private javax.swing.JMenuItem jMenuItemEditProv;
    private javax.swing.JMenuItem jMenuItemEditarCliente;
    private javax.swing.JMenuItem jMenuItemGenBackup;
    private javax.swing.JMenuItem jMenuItemNewProd;
    private javax.swing.JMenuItem jMenuItemNewProv;
    private javax.swing.JMenuItem jMenuItemNuevaEmpresaCliente;
    private javax.swing.JMenuItem jMenuItemNuevaPersonaCliente;
    private javax.swing.JMenuItem jMenuItemRestoreBackup;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JRadioButtonMenuItem jRadioButtonClientes;
    private javax.swing.JRadioButtonMenuItem jRadioButtonGeneral;
    private javax.swing.JRadioButtonMenuItem jRadioButtonProductos;
    private javax.swing.JRadioButtonMenuItem jRadioButtonProveedores;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton limpiarBusquedaClientesjButton;
    private javax.swing.JButton limpiarBusquedaProveedorjButton;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JCheckBox personasjCheckBox;
    private javax.swing.JPanel productosjPanel;
    private javax.swing.JTable productosjTable;
    private javax.swing.JPanel proveedoresjPanel;
    private javax.swing.JTable proveedoresjTable;
    private javax.swing.ButtonGroup view;
    // End of variables declaration//GEN-END:variables

    public JButton getBorrarCliente() {
        return borrarCliente;
    }

    public JTextField getBuscarClienteNombrejTextField() {
        return buscarClienteNombrejTextField;
    }

    public JPanel getClientesjPanel() {
        return clientesjPanel;
    }

    public JTable getClientesjTable() {
        return clientesjTable;
    }

    public PersistenceManagerFactory getConexion() {
        return conexion;
    }

    public JButton getEditarCliente() {
        return editarCliente;
    }

    public JCheckBox getEmpresasjCheckBox() {
        return empresasjCheckBox;
    }

    public JButton getjButtonNuevaEmpresa() {
        return jButtonNuevaEmpresa;
    }

    public JButton getjButtonNuevaPersona() {
        return jButtonNuevaPersona;
    }

    public JLabel getjLabel2() {
        return jLabel2;
    }

    public JMenu getjMenu1() {
        return jMenu1;
    }

    public JMenu getjMenu2() {
        return jMenu2;
    }

    public JMenu getjMenu3() {
        return jMenu3;
    }

    public JMenu getjMenu4() {
        return jMenu4;
    }

    public JMenu getjMenu5() {
        return jMenu5;
    }

    public JMenuItem getjMenuItem1() {
        return jMenuItem1;
    }

    public JMenuItem getjMenuItemBorrarCliente() {
        return jMenuItemBorrarCliente;
    }

    public JMenuItem getjMenuItemEditProd() {
        return jMenuItemEditProd;
    }

    public JMenuItem getjMenuItemEditProv() {
        return jMenuItemEditProv;
    }

    public JMenuItem getjMenuItemEditarCliente() {
        return jMenuItemEditarCliente;
    }

    public JMenuItem getjMenuItemNewProd() {
        return jMenuItemNewProd;
    }

    public JMenuItem getjMenuItemNewProv() {
        return jMenuItemNewProv;
    }

    public JMenuItem getjMenuItemNuevaEmpresaCliente() {
        return jMenuItemNuevaEmpresaCliente;
    }

    public JMenuItem getjMenuItemNuevaPersonaCliente() {
        return jMenuItemNuevaPersonaCliente;
    }

    public JPanel getjPanel1() {
        return jPanel1;
    }

    public JRadioButtonMenuItem getjRadioButtonClientes() {
        return jRadioButtonClientes;
    }

    public JRadioButtonMenuItem getjRadioButtonProductos() {
        return jRadioButtonProductos;
    }

    public JRadioButtonMenuItem getjRadioButtonProveedores() {
        return jRadioButtonProveedores;
    }

    public JScrollPane getjScrollPane2() {
        return jScrollPane2;
    }

    public JSeparator getjSeparator1() {
        return jSeparator1;
    }

    public JSeparator getjSeparator2() {
        return jSeparator2;
    }

    public JTabbedPane getjTabbedPane1() {
        return jTabbedPane1;
    }

    public JCheckBox getPersonasjCheckBox() {
        return personasjCheckBox;
    }

    public JPanel getProductosjPanel() {
        return productosjPanel;
    }

    public JPanel getProveedoresjPanel() {
        return proveedoresjPanel;
    }

    public ButtonGroup getView() {
        return view;
    }    

    public JTextField getBuscarClienteDNIjTextField() {
        return buscarClienteDNIjTextField;
    }

    public JTextField getBuscarPrimeraParteCuit() {
        return buscarClientePrimeraParteCuit;
    }

    public JTextField getBuscarSegundaParteCuit() {
        return buscarClienteSegundaParteCuit;
    }

    public JTextField getBuscarTerceraParteCuit() {
        return buscarClienteTerceraParteCuit;
    }

    public JTextField getBuscarClientePrimeraParteCuit() {
        return buscarClientePrimeraParteCuit;
    }

    public JTextField getBuscarClienteSegundaParteCuit() {
        return buscarClienteSegundaParteCuit;
    }

    public JTextField getBuscarClienteTerceraParteCuit() {
        return buscarClienteTerceraParteCuit;
    }

    public JButton getLimpiarBusquedajButton() {
        return limpiarBusquedaClientesjButton;
    }

    public JButton getBorrarProveedor() {
        return borrarProveedor;
    }

    public JButton getjButtonNuevoProveedor() {
        return jButtonNuevoProveedor;
    }

    public JTable getProveedoresjTable() {
        return proveedoresjTable;
    }

    public JTextField getBuscarProveedorNombrejTextField() {
        return buscarProveedorNombrejTextField;
    }

    public JTextField getBuscarProveedorPrimeraParteCuit() {
        return buscarProveedorPrimeraParteCuit;
    }

    public JTextField getBuscarProveedorSegundaParteCuit() {
        return buscarProveedorSegundaParteCuit;
    }

    public JTextField getBuscarProveedorTerceraParteCuit() {
        return buscarProveedorTerceraParteCuit;
    }

    public JButton getEditarProveedor() {
        return editarProveedor;
    }

    public JButton getLimpiarBusquedaProveedorjButton() {
        return limpiarBusquedaProveedorjButton;
    }

    public JMenuItem getjMenuItemBorrarProveedor() {
        return jMenuItemBorrarProveedor;
    }


    public JMenuItem getjMenuItemGenBackup() {
        return jMenuItemGenBackup;
    }

    public JMenuItem getjMenuItemRestoreBackup() {
        return jMenuItemRestoreBackup;
    }

    public JButton getjButtonBorrarProducto() {
        return jButtonBorrarProducto;
    }

    public JButton getjButtonEditarProducto() {
        return jButtonEditarProducto;
    }

    public JButton getjButtonNuevoProducto() {
        return jButtonNuevoProducto;
    }

    public JTable getProductosjTable() {
        return productosjTable;
    }

    

    public void mostrarAlertaEventosDia(final AStock aStock) {

        SwingUtilities.invokeLater(new Runnable() {

            @Override
            public void run() {
                if (JOptionPane.showConfirmDialog(aStock, "Existen Eventos para hoy, ¿Desea ver su agenda?",
                        "Alerta agenda", JOptionPane.OK_CANCEL_OPTION,
                        JOptionPane.INFORMATION_MESSAGE,
                        new ImageIcon(getClass().getResource("/img/important.png"))) == JOptionPane.OK_OPTION) {

                    //muestro la agenda
                    MediadorAgenda agenda = MediadorAgenda.getInstance();
                }
            }
        });
    }

    public void mostrarAlertaEvento(final AStock aStock, final Evento evento) {

        SwingUtilities.invokeLater(new Runnable() {

            @Override
            public void run() {
                AlertaEventoDialog aed = new AlertaEventoDialog(aStock, true);
                aed.setEvento(evento);
                aed.setLocationRelativeTo(aStock);
                aed.show();
            }
        });
    }

    public void setAccesosBD(AccesosBD accesosBD) {
        this.accesosBD = accesosBD;
    }
        
}
