/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Agenda.java
 *
 * Created on 16-oct-2009, 15:49:00
 */
package agili.astock.Agenda;

import javax.swing.*;

/**
 *
 * @author Alvaro Gili
 */
public class Agenda extends javax.swing.JFrame {

    /** Creates new form Agenda */
    public Agenda() {
        initComponents();
        this.setIconImage(new ImageIcon(getClass().getResource("/img/logo_AStock_sin_fondo.png")).getImage());
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButtonMesAnterior = new javax.swing.JButton();
        jTextFieldMes = new javax.swing.JTextField();
        jButtonMesSiguiente = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jSpinnerAño = new javax.swing.JSpinner();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableCalendario = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableDiaAgenda = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jButtonNuevoEvento = new javax.swing.JButton();
        jButtonBorrarEvento = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabelFechaYHora = new javax.swing.JLabel();
        jSpinnerHoraYFechaNuevoEvento = new javax.swing.JSpinner();
        jComboBoxCategorias = new javax.swing.JComboBox();
        jLabelCategoria = new javax.swing.JLabel();
        jLabelDescripcion = new javax.swing.JLabel();
        jCheckBoxAlarma = new javax.swing.JCheckBox();
        jButtonCancelarGuardado = new javax.swing.JButton();
        jButtonGuardarEvento = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextFieldDescripcion = new javax.swing.JTextArea();
        jLabelImagen = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Agenda");
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jButtonMesAnterior.setText("<");

        jTextFieldMes.setEditable(false);
        jTextFieldMes.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jButtonMesSiguiente.setText(">");

        jLabel1.setText("Año:");

        jSpinnerAño.setModel(new javax.swing.SpinnerNumberModel());
        jSpinnerAño.setEditor(new javax.swing.JSpinner.NumberEditor(jSpinnerAño, ""));

        jTableCalendario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Domingo", "Lunes", "Martes", "Miécoles", "Jueves", "Viernes", "Sabado"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Short.class, java.lang.Short.class, java.lang.Short.class, java.lang.Short.class, java.lang.Short.class, java.lang.Short.class, java.lang.Short.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableCalendario.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTableCalendario.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTableCalendario);
        jTableCalendario.getColumnModel().getColumn(0).setResizable(false);
        jTableCalendario.getColumnModel().getColumn(1).setResizable(false);
        jTableCalendario.getColumnModel().getColumn(2).setResizable(false);
        jTableCalendario.getColumnModel().getColumn(3).setResizable(false);
        jTableCalendario.getColumnModel().getColumn(4).setResizable(false);
        jTableCalendario.getColumnModel().getColumn(5).setResizable(false);
        jTableCalendario.getColumnModel().getColumn(6).setResizable(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 375, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButtonMesAnterior)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldMes, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonMesSiguiente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSpinnerAño, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonMesAnterior)
                    .addComponent(jButtonMesSiguiente)
                    .addComponent(jSpinnerAño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTableDiaAgenda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Hora", "Descripción", "Categoría", "Alarma"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableDiaAgenda.setRowHeight(60);
        jTableDiaAgenda.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTableDiaAgenda.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(jTableDiaAgenda);
        jTableDiaAgenda.getColumnModel().getColumn(0).setResizable(false);
        jTableDiaAgenda.getColumnModel().getColumn(0).setPreferredWidth(10);
        jTableDiaAgenda.getColumnModel().getColumn(1).setMinWidth(140);
        jTableDiaAgenda.getColumnModel().getColumn(1).setPreferredWidth(140);
        jTableDiaAgenda.getColumnModel().getColumn(2).setResizable(false);
        jTableDiaAgenda.getColumnModel().getColumn(2).setPreferredWidth(15);
        jTableDiaAgenda.getColumnModel().getColumn(3).setResizable(false);
        jTableDiaAgenda.getColumnModel().getColumn(3).setPreferredWidth(10);

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jButtonNuevoEvento.setText("Nuevo Evento");
        jButtonNuevoEvento.setEnabled(false);

        jButtonBorrarEvento.setText("Borrar");
        jButtonBorrarEvento.setEnabled(false);

        jPanel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabelFechaYHora.setText("Fecha y Hora:");

        jSpinnerHoraYFechaNuevoEvento.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(), null, null, java.util.Calendar.MINUTE));

        jComboBoxCategorias.setMaximumRowCount(30);
        jComboBoxCategorias.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Académico", "Aniversario", "Clientes", "Cumpleaños", "Día festivo", "Feriado", "Importante", "Llamada", "Médico", "Ocio", "Proveedores", "Proyecto", "Recordatorio", "Trabajo", "Vacaciones", "Viaje", "Otro" }));

        jLabelCategoria.setText("Categoria:");

        jLabelDescripcion.setText("Descripción:");

        jCheckBoxAlarma.setText("Avisarme 10 minutos antes");

        jButtonCancelarGuardado.setText("Cancelar");

        jButtonGuardarEvento.setText("Guardar");

        jScrollPane3.setAutoscrolls(true);
        jScrollPane3.setEnabled(false);

        jTextFieldDescripcion.setColumns(20);
        jTextFieldDescripcion.setRows(5);
        jScrollPane3.setViewportView(jTextFieldDescripcion);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBoxAlarma)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 349, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabelFechaYHora)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSpinnerHoraYFechaNuevoEvento, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelCategoria)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxCategorias, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabelDescripcion)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabelImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 130, Short.MAX_VALUE)
                        .addComponent(jButtonGuardarEvento)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonCancelarGuardado)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelFechaYHora)
                    .addComponent(jSpinnerHoraYFechaNuevoEvento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelCategoria)
                    .addComponent(jComboBoxCategorias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabelDescripcion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBoxAlarma)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtonCancelarGuardado)
                        .addComponent(jButtonGuardarEvento))
                    .addComponent(jLabelImagen, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButtonNuevoEvento)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 211, Short.MAX_VALUE)
                        .addComponent(jButtonBorrarEvento)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonNuevoEvento)
                    .addComponent(jButtonBorrarEvento))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 516, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 463, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public JButton getjButtonMesSiguiente() {
        return jButtonMesSiguiente;
    }

    public JButton getjButtonMesAnterior() {
        return jButtonMesAnterior;
    }

    public JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    public JSpinner getjSpinnerAño() {
        return jSpinnerAño;
    }

    public JTable getjTableCalendario() {
        return jTableCalendario;
    }

    public JTextField getjTextFieldMes() {
        return jTextFieldMes;
    }

    public JButton getjButtonBorrarEvento() {
        return jButtonBorrarEvento;
    }

    public void setjButtonBorrarEvento(JButton jButtonBorrarEvento) {
        this.jButtonBorrarEvento = jButtonBorrarEvento;
    }

    public JButton getjButtonNuevoEvento() {
        return jButtonNuevoEvento;
    }

    public void setjButtonNuevoEvento(JButton jButtonNuevoEvento) {
        this.jButtonNuevoEvento = jButtonNuevoEvento;
    }

    public JTable getjTableDiaAgenda() {
        return jTableDiaAgenda;
    }

    public void setjTableDiaAgenda(JTable jTableDiaAgenda) {
        this.jTableDiaAgenda = jTableDiaAgenda;
    }

    public JButton getjButtonCancelarGuardado() {
        return jButtonCancelarGuardado;
    }

    public void setjButtonCancelarGuardado(JButton jButtonCancelarGuardado) {
        this.jButtonCancelarGuardado = jButtonCancelarGuardado;
    }

    public JButton getjButtonGuardarEvento() {
        return jButtonGuardarEvento;
    }

    public void setjButtonGuardarEvento(JButton jButtonGuardarEvento) {
        this.jButtonGuardarEvento = jButtonGuardarEvento;
    }

    public JCheckBox getjCheckBoxAlarma() {
        return jCheckBoxAlarma;
    }

    public void setjCheckBoxAlarma(JCheckBox jCheckBoxAlarma) {
        this.jCheckBoxAlarma = jCheckBoxAlarma;
    }

    public JComboBox getjComboBoxCategorias() {
        return jComboBoxCategorias;
    }

    public void setjComboBoxCategorias(JComboBox jComboBoxCategorias) {
        this.jComboBoxCategorias = jComboBoxCategorias;
    }

    public JLabel getjLabelCategoria() {
        return jLabelCategoria;
    }

    public void setjLabelCategoria(JLabel jLabelCategoria) {
        this.jLabelCategoria = jLabelCategoria;
    }

    public JLabel getjLabelDescripcion() {
        return jLabelDescripcion;
    }

    public void setjLabelDescripcion(JLabel jLabelDescripcion) {
        this.jLabelDescripcion = jLabelDescripcion;
    }

    public JLabel getjLabelFechaYHora() {
        return jLabelFechaYHora;
    }

    public void setjLabelFechaYHora(JLabel jLabelFechaYHora) {
        this.jLabelFechaYHora = jLabelFechaYHora;
    }

    public JTextArea getjTextFieldDescripcion() {
        return jTextFieldDescripcion;
    }

    public void setjTextFieldDescripcion(JTextArea jTextFieldDescripcion) {
        this.jTextFieldDescripcion = jTextFieldDescripcion;
    }

    public JSpinner getjSpinnerHoraYFechaNuevoEvento() {
        return jSpinnerHoraYFechaNuevoEvento;
    }

    public void setjSpinnerHoraYFechaNuevoEvento(JSpinner jSpinnerHoraYFechaNuevoEvento) {
        this.jSpinnerHoraYFechaNuevoEvento = jSpinnerHoraYFechaNuevoEvento;
    }

    public JLabel getjLabelImagen() {
        return jLabelImagen;
    }

    public void setjLabelImagen(JLabel jLabelImagen) {
        this.jLabelImagen = jLabelImagen;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBorrarEvento;
    private javax.swing.JButton jButtonCancelarGuardado;
    private javax.swing.JButton jButtonGuardarEvento;
    private javax.swing.JButton jButtonMesAnterior;
    private javax.swing.JButton jButtonMesSiguiente;
    private javax.swing.JButton jButtonNuevoEvento;
    private javax.swing.JCheckBox jCheckBoxAlarma;
    private javax.swing.JComboBox jComboBoxCategorias;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelCategoria;
    private javax.swing.JLabel jLabelDescripcion;
    private javax.swing.JLabel jLabelFechaYHora;
    private javax.swing.JLabel jLabelImagen;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSpinner jSpinnerAño;
    private javax.swing.JSpinner jSpinnerHoraYFechaNuevoEvento;
    private javax.swing.JTable jTableCalendario;
    private javax.swing.JTable jTableDiaAgenda;
    private javax.swing.JTextArea jTextFieldDescripcion;
    private javax.swing.JTextField jTextFieldMes;
    // End of variables declaration//GEN-END:variables
}
