/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AlertaEventoDialog.java
 *
 * Created on 29-oct-2009, 12:08:11
 */

package agili.astock.Agenda;

import agili.astock.BD.Agenda.Evento;
import javax.swing.ImageIcon;

/**
 *
 * @author Alvaro Gili
 */
public class AlertaEventoDialog extends javax.swing.JDialog {
    /** A return status code - returned if Cancel button has been pressed */
    public static final int RET_CANCEL = 0;
    /** A return status code - returned if OK button has been pressed */
    public static final int RET_OK = 1;

    /** Creates new form AlertaEventoDialog */
    public AlertaEventoDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();        
    }

    /** @return the return status of this dialog - one of RET_OK or RET_CANCEL */
    public int getReturnStatus() {
        return returnStatus;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        okButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabelImagen = new javax.swing.JLabel();
        jLabelTipoEvento = new javax.swing.JLabel();
        jLabelFechaYHora = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaDescripcion = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Aviso de nuevo evento");
        setAlwaysOnTop(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        okButton.setText("Cerrar");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabelImagen.setName(""); // NOI18N

        jLabelTipoEvento.setText("Hoy ");

        jLabelFechaYHora.setText("Fecha y hora de inicio del evento: ");

        jTextAreaDescripcion.setColumns(20);
        jTextAreaDescripcion.setEditable(false);
        jTextAreaDescripcion.setRows(5);
        jScrollPane1.setViewportView(jTextAreaDescripcion);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelFechaYHora, javax.swing.GroupLayout.DEFAULT_SIZE, 415, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelTipoEvento, javax.swing.GroupLayout.DEFAULT_SIZE, 335, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelTipoEvento)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabelImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelFechaYHora)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel3.setText("En instantes ...");

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 14));
        jLabel2.setText("Aviso de evento");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/importante.gif"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(195, 195, 195)
                        .addComponent(okButton, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3)))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(okButton)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        doClose(RET_OK);
    }//GEN-LAST:event_okButtonActionPerformed

    /** Closes the dialog */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        doClose(RET_CANCEL);
    }//GEN-LAST:event_closeDialog

    private void doClose(int retStatus) {
        returnStatus = retStatus;
        setVisible(false);
        dispose();
    }

    /**
     * recibe el evento y completa la interface con los datos de este
     * @param evento Evento
     */
    public void setEvento(Evento evento) {
        this.evento = evento;
        //dependiendo del elegido coloco la imagen
        String categoria = evento.appGetCategoria();
        jTextAreaDescripcion.setText(evento.appGetDescripción());
        jLabelFechaYHora.setText("Fecha y hora de inicio del evento:" + evento.appGetHoraYFechaHowString() + " hs.");
        if (categoria == null) {
            jLabelImagen.setIcon(new ImageIcon(getClass().getResource("/img/flag.png")));
            jLabelTipoEvento.setText("Recuerda...");
        } else if (categoria.equals("Académico")) {
            jLabelImagen.setIcon(new ImageIcon(getClass().getResource("/img/books_048.png")));
            jLabelTipoEvento.setText("Recuerda el estudio...");
        } else if (categoria.equals("Aniversario")) {
            jLabelImagen.setIcon(new ImageIcon(getClass().getResource("/img/package_favorite.png")));
            jLabelTipoEvento.setText("Recuerda el aniversario...");
        } else if (categoria.equals("Clientes")) {
            jLabelImagen.setIcon(new ImageIcon(getClass().getResource("/img/system-users.png")));
            jLabelTipoEvento.setText("Recuerda, debes hablar con un cliente...");
        } else if (categoria.equals("Cumpleaños")) {
            jLabelImagen.setIcon(new ImageIcon(getClass().getResource("/img/cumpleaños.png")));
            jLabelTipoEvento.setText("Recuerda su cumpleaños...");
        } else if (categoria.equals("Día festivo")) {
            jLabelImagen.setIcon(new ImageIcon(getClass().getResource("/img/balloons48.png")));
            jLabelTipoEvento.setText("Recuerda, hoy es dia festivo...");
        } else if (categoria.equals("Feriado")) {
            jLabelImagen.setIcon(new ImageIcon(getClass().getResource("/img/date48.png")));
            jLabelTipoEvento.setText("Recuerda que es feriado...");
        } else if (categoria.equals("Importante")) {
            jLabelImagen.setIcon(new ImageIcon(getClass().getResource("/img/important_calendar.png")));
            jLabelTipoEvento.setText("Recuerda esto que es importante...");
        } else if (categoria.equals("Llamada")) {
            jLabelImagen.setIcon(new ImageIcon(getClass().getResource("/img/internet-telephony.png")));
            jLabelTipoEvento.setText("Recuerda, debes hacer una llamada...");
        } else if (categoria.equals("Médico")) {
            jLabelImagen.setIcon(new ImageIcon(getClass().getResource("/img/Ambulance.png")));
            jLabelTipoEvento.setText("Recuerda, debes ir al doctor...");
        } else if (categoria.toString().equals("Ocio")) {
            jLabelImagen.setIcon(new ImageIcon(getClass().getResource("/img/kteatime.png")));
            jLabelTipoEvento.setText("Recuerda, que debes descansar...");
        } else if (categoria.toString().equals("Proveedores")) {
            jLabelImagen.setIcon(new ImageIcon(getClass().getResource("/img/LorryGreen.png")));
            jLabelTipoEvento.setText("Recuerda, debes hablar con un proveedor...");
        } else if (categoria.toString().equals("Proyecto")) {
            jLabelImagen.setIcon(new ImageIcon(getClass().getResource("/img/file-roller.png")));
            jLabelTipoEvento.setText("Recuerda, tienes un proyecto pendiente...");
        } else if (categoria.toString().equals("Recordatorio")) {
            jLabelImagen.setIcon(new ImageIcon(getClass().getResource("/img/knotes.png")));
            jLabelTipoEvento.setText("Recuerda...");
        } else if (categoria.toString().equals("Trabajo")) {
            jLabelImagen.setIcon(new ImageIcon(getClass().getResource("/img/agt_utilities.png")));
            jLabelTipoEvento.setText("Recuerda, debes hacer un trabajo...");
        } else if (categoria.toString().equals("Vacaciones")) {
            jLabelImagen.setIcon(new ImageIcon(getClass().getResource("/img/Umbrella-48x48.png")));
            jLabelTipoEvento.setText("Recuerda tus vacaciones!!!...");
        } else if (categoria.toString().equals("Viaje")) {
            jLabelImagen.setIcon(new ImageIcon(getClass().getResource("/img/plane.png")));
            jLabelTipoEvento.setText("Recuerda que debes hacer un viaje...");
        } else {
            jLabelImagen.setIcon(new ImageIcon(getClass().getResource("/img/flag.png")));
            jLabelTipoEvento.setText("Recuerda...");
        }
    }    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelFechaYHora;
    private javax.swing.JLabel jLabelImagen;
    private javax.swing.JLabel jLabelTipoEvento;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaDescripcion;
    private javax.swing.JButton okButton;
    // End of variables declaration//GEN-END:variables

    private int returnStatus = RET_CANCEL;

    private Evento evento;
}
