/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Configuracion.java
 *
 * Created on 17-nov-2009, 10:12:10
 */
package agili.astock.Herramientas;

import BD.Utilidades.PasswordAdmin;
import BD.Utilidades.Skin;
import agili.astock.BD.AccesosBD;
import java.util.HashMap;
import java.util.Vector;
import javax.jdo.JDOHelper;
import javax.jdo.PersistenceManager;
import javax.jdo.PersistenceManagerFactory;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import org.pushingpixels.substance.api.SubstanceLookAndFeel;
import org.pushingpixels.substance.api.skin.SkinInfo;

/**
 *
 * @author Alvaro Gili
 */
public class Configuracion extends javax.swing.JDialog {

    private String currentLookAndFeel;
    private DatosDeConfiguracion ddc = DatosDeConfiguracion.getInstance();
    private PersistenceManagerFactory conexion;
    private PersistenceManager persistenceManager;
    private AccesosBD abd = AccesosBD.getInstance();

    /** Creates new form Configuracion */
    public Configuracion(java.awt.Frame parent, boolean modal, PersistenceManagerFactory conexion, PersistenceManager persistenceManager) {
        super(parent, modal);
        initComponents();
        Vector<String> items = new Vector<String>(SubstanceLookAndFeel.getAllSkins().keySet());
        for (int i = 0; i < items.size(); i++) {
            jComboBoxLookAndFeel.addItem(items.get(i));
        }

        currentLookAndFeel = SubstanceLookAndFeel.getCurrentSkin().getDisplayName();
        jComboBoxLookAndFeel.setSelectedItem(currentLookAndFeel);

        jCheckBoxEventosAlInicio.setSelected(ddc.isVerificarEventosAlInicio());
        jTextFieldIPYPuerto.setText(ddc.getURLBD());
        jTextFieldUsuario.setText(ddc.getUsuarioBD());

        this.conexion = conexion;
        this.persistenceManager = persistenceManager;

        PasswordAdmin pa = (PasswordAdmin) abd.getObjeto(PasswordAdmin.class, null);
        if(pa != null)
            jCheckBoxContraseñaInicio.setSelected(pa.appGetSolicitarPassInicio());
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPaneConf = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jCheckBoxEventosAlInicio = new javax.swing.JCheckBox();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jComboBoxLookAndFeel = new javax.swing.JComboBox();
        jButtonSkin = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldIPYPuerto = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldUsuario = new javax.swing.JTextField();
        jButtonCambiarPass = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jCheckBoxContraseñaInicio = new javax.swing.JCheckBox();
        jButtonCambiarPassAdmin = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jButtonGuardar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Agenda"));

        jCheckBoxEventosAlInicio.setText("Verificar Eventos al inicio");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jCheckBoxEventosAlInicio)
                .addContainerGap(120, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jCheckBoxEventosAlInicio)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Visualización"));

        jLabel1.setText("Piel de la aplicación");

        jButtonSkin.setText("Probar Skin");
        jButtonSkin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSkinActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jComboBoxLookAndFeel, 0, 249, Short.MAX_VALUE)
                    .addComponent(jButtonSkin, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBoxLookAndFeel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonSkin))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(55, Short.MAX_VALUE))
        );

        jTabbedPaneConf.addTab("Preferencias", jPanel1);

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Conexión base de datos"));

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/network-server-database.png"))); // NOI18N

        jLabel2.setText("IP y puerto:");

        jLabel3.setText("Usuario:");

        jButtonCambiarPass.setText("Cambiar contraseña");
        jButtonCambiarPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCambiarPassActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldUsuario)
                            .addComponent(jTextFieldIPYPuerto, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jButtonCambiarPass, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jTextFieldIPYPuerto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(15, 15, 15)
                                .addComponent(jTextFieldUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(jLabel3))
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addComponent(jButtonCambiarPass)))
                .addContainerGap())
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Contraseña de administrador"));

        jCheckBoxContraseñaInicio.setText("Utilizar contraseña de inicio");
        jCheckBoxContraseñaInicio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jButtonCambiarPassAdmin.setText("Cambiar contraseña");
        jButtonCambiarPassAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCambiarPassAdminActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jButtonCambiarPassAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, 243, Short.MAX_VALUE))
                    .addComponent(jCheckBoxContraseñaInicio, javax.swing.GroupLayout.DEFAULT_SIZE, 253, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jCheckBoxContraseñaInicio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addComponent(jButtonCambiarPassAdmin))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPaneConf.addTab("Seguridad", jPanel4);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/application-exit.png"))); // NOI18N
        jButton1.setText("Cancelar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/agt_utilities32.png"))); // NOI18N

        jButtonGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/media-floppy.png"))); // NOI18N
        jButtonGuardar.setText("Guardar");
        jButtonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPaneConf, javax.swing.GroupLayout.DEFAULT_SIZE, 310, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                        .addComponent(jButtonGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jTabbedPaneConf, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton1)
                        .addComponent(jButtonGuardar)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // Get the skin info object based on
        // the selected skin display name
        SkinInfo skinInfo = SubstanceLookAndFeel.getAllSkins().get(currentLookAndFeel);
        // Set the global skin based on the
        // skin class name.
        SubstanceLookAndFeel.setSkin(skinInfo.getClassName());
        SwingUtilities.updateComponentTreeUI(Configuracion.this);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButtonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuardarActionPerformed

        if (!currentLookAndFeel.equals((String) jComboBoxLookAndFeel.getSelectedItem())) {
            // Get the skin info object based on
            // the selected skin display name
            SkinInfo skinInfo = SubstanceLookAndFeel.getAllSkins().get((String) jComboBoxLookAndFeel.getSelectedItem());
            // Set the global skin based on the
            // skin class name.
            SubstanceLookAndFeel.setSkin(skinInfo.getClassName());
            SwingUtilities.updateComponentTreeUI(Configuracion.this);
            
            Skin skin = (Skin) abd.getObjeto(Skin.class, "skinType == \'aplicacion\'");
            skin.appSetSkinName(skinInfo.getDisplayName());

            abd.actualizarObjeto(Skin.class, skin, "skinType == \'aplicacion\'");
        }

        ddc.setURLBD(jTextFieldIPYPuerto.getText());
        ddc.setUsuarioBD(jTextFieldUsuario.getText());
        ddc.setVerificarEventosAlInicio(jCheckBoxEventosAlInicio.isSelected());

        //////////////////////////////////////////////////////
        //iniciando transacción con la base de datos
        HashMap<String, String> properties = new HashMap<String, String>();
        properties.put("javax.jdo.PersistenceManagerFactoryClass", "org.jpox.jdo.JDOPersistenceManagerFactory");
        properties.put("javax.jdo.option.ConnectionDriverName", "org.gjt.mm.mysql.Driver");
        ////////para leer y escribir fuera de una transacción
        properties.put("javax.jdo.option.NontransactionalRead", "true");
        properties.put("javax.jdo.option.NontransactionalWrite", "true");
        //////////////////////////////////////////////////////
        properties.put("javax.jdo.option.ConnectionURL", "jdbc:mysql://" + ddc.getURLBD() + "/astock");
        properties.put("javax.jdo.option.ConnectionUserName", ddc.getUsuarioBD());
        properties.put("javax.jdo.option.ConnectionPassword", ddc.getContraseñaBD());
        properties.put("org.jpox.autoCreateTables", "true");
        properties.put("org.jpox.autoCreateColumns", "true");
        properties.put("org.jpox.validateTables", "false");
        properties.put("org.jpox.validateConstraints", "true");
        try {
            conexion = JDOHelper.getPersistenceManagerFactory(properties);
            persistenceManager = conexion.getPersistenceManager();
            PasswordAdmin pa = (PasswordAdmin) abd.getObjeto(PasswordAdmin.class, null);
            pa.appSetSolicitarPassInicio(jCheckBoxContraseñaInicio.isSelected());
            abd.actualizarObjeto(PasswordAdmin.class, pa, null);
        jCheckBoxContraseñaInicio.setSelected(pa.appGetSolicitarPassInicio());

            if (ddc.guardarConfiguracion()) {
                JOptionPane.showMessageDialog(this,
                            "Configuración cambiada correctamente.", "Confirmación", JOptionPane.INFORMATION_MESSAGE,
                            new ImageIcon(getClass().getResource("/img/dialog-ok.png")));
                dispose();
            } else {
                 JOptionPane.showMessageDialog(this,
                        "Error al guardar la configuración, por favor borre el archivo \"Configuracion.xml\" e intente guardar nuevamente"
                        , "Error", JOptionPane.ERROR_MESSAGE,
                        new ImageIcon(getClass().getResource("/img/error.gif")));
            }
        } catch (Exception e) {
             JOptionPane.showMessageDialog(this,
                        "Los datos de conexión con la base de datos son incorrectos, por favor verifique."
                        , "Error", JOptionPane.ERROR_MESSAGE,
                        new ImageIcon(getClass().getResource("/img/error.gif")));
        }
    }//GEN-LAST:event_jButtonGuardarActionPerformed

    private void jButtonCambiarPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCambiarPassActionPerformed
        CambiarContraseña cambiarContraseña = new CambiarContraseña(CambiarContraseña.tipoContraseña.PASS_BD);
        cambiarContraseña.setModal(true);
        cambiarContraseña.setLocationRelativeTo(this);
        cambiarContraseña.setVisible(true);

        if (cambiarContraseña.isPasswordChanged()) {
            jButtonCambiarPass.setText("Contraseña cambiada correctamente");
            jButtonCambiarPass.setIcon(new ImageIcon(getClass().getResource("/img/dialog-ok-apply.png")));
        } else {
            jButtonCambiarPass.setText("Cambiar contraseña");
            jButtonCambiarPass.setIcon(null);
        }
}//GEN-LAST:event_jButtonCambiarPassActionPerformed

    private void jButtonSkinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSkinActionPerformed
        // Get the skin info object based on
        // the selected skin display name
        SkinInfo skinInfo = SubstanceLookAndFeel.getAllSkins().get((String) jComboBoxLookAndFeel.getSelectedItem());
        // Set the global skin based on the
        // skin class name.
        SubstanceLookAndFeel.setSkin(skinInfo.getClassName());
        SwingUtilities.updateComponentTreeUI(Configuracion.this);
}//GEN-LAST:event_jButtonSkinActionPerformed

    private void jButtonCambiarPassAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCambiarPassAdminActionPerformed
        CambiarContraseña cambiarContraseña = new CambiarContraseña(CambiarContraseña.tipoContraseña.PASS_ADMIN);
        cambiarContraseña.setModal(true);
        cambiarContraseña.setLocationRelativeTo(this);
        cambiarContraseña.setVisible(true);

        if (cambiarContraseña.isPasswordChanged()) {
            jButtonCambiarPassAdmin.setText("Contraseña cambiada correctamente");
            jButtonCambiarPassAdmin.setIcon(new ImageIcon(getClass().getResource("/img/dialog-ok-apply.png")));
        } else {
            jButtonCambiarPassAdmin.setText("Cambiar contraseña");
            jButtonCambiarPassAdmin.setIcon(null);
        }
    }//GEN-LAST:event_jButtonCambiarPassAdminActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonCambiarPass;
    private javax.swing.JButton jButtonCambiarPassAdmin;
    private javax.swing.JButton jButtonGuardar;
    private javax.swing.JButton jButtonSkin;
    private javax.swing.JCheckBox jCheckBoxContraseñaInicio;
    private javax.swing.JCheckBox jCheckBoxEventosAlInicio;
    private javax.swing.JComboBox jComboBoxLookAndFeel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JTabbedPane jTabbedPaneConf;
    private javax.swing.JTextField jTextFieldIPYPuerto;
    private javax.swing.JTextField jTextFieldUsuario;
    // End of variables declaration//GEN-END:variables
}
