/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Procesando.java
 *
 * Created on 16-mar-2010, 10:53:16
 */
package agili.astock.Herramientas;

import javax.swing.JFrame;

/**
 * Dialogo generico para mostrar que se está procesando
 * @author Alvaro Gili
 */
public class Procesando extends javax.swing.JDialog {

    /**
     * Constructor
     * @param thread thread a ejecutar para el procesamiento
     * @param text Texto a escribir en el dialogo
     */
    public Procesando(Thread thread, String text) {
        initComponents();
        jLabelMensaje.setText(text);
        this.thread = thread;
        if (thread instanceof GenerarBackupThread) {
            ((GenerarBackupThread) thread).setProcesando(this);
        }else if(thread instanceof RestaurarBackupThread){
            ((RestaurarBackupThread) thread).setProcesando(this);
        }
    }

    /**
     * Constructor
     * @param text Texto a escribir en el dialogo
     */
    public Procesando(String text){
        initComponents();
        jLabelMensaje.setText(text);
    }

    public void mostrar(boolean show, JFrame parent) {                

        if (show) {
            if(thread != null)
                thread.start();
            this.setLocationRelativeTo(parent);
            this.setAlwaysOnTop(true);
            this.parent = parent;
        }        
        this.setModal(show);
        this.setVisible(show);
    }


    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabelMensaje = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Procesando...");
        setResizable(false);
        setUndecorated(true);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/waiting.gif"))); // NOI18N

        jLabelMensaje.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelMensaje.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelMensaje.setText("jLabel2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelMensaje, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabelMensaje)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelMensaje;
    // End of variables declaration//GEN-END:variables
    private Thread thread = null;
    private JFrame parent;
}
