/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * GenerarBackupBD.java
 *
 * Created on 15-mar-2010, 19:20:52
 */
package Herramientas;

import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileFilter;

/**
 *
 * @author Alvaro Gili
 */
public class RestaurarBackupBD extends javax.swing.JDialog {

    public RestaurarBackupBD(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        jFileChooser.setFileFilter(new FileFilter() {

            @Override
            public boolean accept(File f) {
                if (f.getName().endsWith(".zip")) {
                    return true;
                } else if (f.isDirectory()) {
                    return true;
                } else {
                    return false;
                }
            }

            @Override
            public String getDescription() {
                return "Archivos comprimidos (*.zip).";
            }
        });

        this.setLocationRelativeTo(parent);       
    }

    public String getFileName() {
        return defaultFileName;
    }

    public String getDirectory() {
        return directory;
    }

    public boolean getAccepted() {
        return accepted;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser = new javax.swing.JFileChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Seleccione la ubicación y el nombre del archivo de backup...");

        jFileChooser.setDialogTitle("");
        jFileChooser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFileChooserActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jFileChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jFileChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jFileChooserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFileChooserActionPerformed
        String s = evt.getActionCommand();
        if (s.equals("ApproveSelection")) {//acepto
            File f = new File(jFileChooser.getCurrentDirectory().getAbsolutePath() + File.separatorChar + jFileChooser.getSelectedFile().getName());
            
            defaultFileName = jFileChooser.getSelectedFile().getName();            
            directory = jFileChooser.getCurrentDirectory().getAbsolutePath();
            accepted = true;
        } else if (s.equals("CancelSelection")) {
            accepted = false;
        }
        dispose();
    }//GEN-LAST:event_jFileChooserActionPerformed
    private boolean accepted = false;
    private String defaultFileName;
    private String directory;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFileChooser jFileChooser;
    // End of variables declaration//GEN-END:variables
}
